BACKGROUNDS = [
               "parchment",
               "wood",
               "window",
               "cloak",
               "wall",
               "tile",
               "tapestry",
               "stone",
               "scroll",
               "gold",
               "wood-panels",
               "stone2",
               "versailles",
               "ceiling",
               "book-cover",
               "stained-glass",
               "window2",
               "white-fabric",
               "magic",
               "flower-frame",
               "canvas",
               "tile2",
               "rust",
               "parchment3",
               "writing",
               "metal-wall",
               "berries",
               "rug",
               "filigree",
               "flower-page",
               "checkers"
             ];

module.exports = BACKGROUNDS;
