COLORS = ["gules",
          "sanguine",
          "azure",
          "celeste",
          "vert",
          "viridian",
          "cendree",
          "lead",
          "sable",
          "white",
          "purpure",
          "murrey",
          "tawny",
          "senois",
          "bisque",
          "rose-pink",
          "carnation",
          "amaranth",
          "argent",
          "or",
          "copper",
          ];

module.exports = COLORS;
