PARTITIONS = ["per-fess",
              "per-pale",
              "per-chevron",
              "per-chevron-reversed",
              "quarterly",
              "per-bend",
              "per-bend-sinister",
              "per-saltire",
              "chaussé",
              "chapé",
              "flaunches",
              "tierced-in-pale",
              "tierced-in-fess",
              "tierced-in-mantle",
              "bordure",
              "paly",
              "barry",
              "bendy",
              "bendy-sinister",
              "enarched-per-fess",
              "enarched-per-pale",
              "angled-per-fess",
              "angled-per-pale",
              "RESET"];

module.exports = PARTITIONS;
